---
- name: Deploy TLS keys
  hosts: all
  user: ansible
  become: true

  tasks:
    - name: Copy public certificate
      ansible.builtin.copy:
        src: ./localhost.crt
        dest: /usr/local/share/ca-certificates/localhost.crt
        mode: '0644'

    - name: Copy secret key
      ansible.builtin.copy:
        src: ./localhost.key
        dest: /root/localhost.key
        mode: '0600'
      when: inventory_hostname in ['gitea','zulip']

    - name: Update certificate store
      ansible.builtin.shell: update-ca-certificates

    - name: Copy gitea nginx config...
      ansible.builtin.copy:
        src: ./templates/gitea
        dest: /etc/nginx/sites-available/gitea
        mode: '0644'
      when: inventory_hostname in ['gitea']

    - name: Link gitea nginx config...
      ansible.builtin.file:
        src: /etc/nginx/sites-available/gitea
        dest: /etc/nginx/sites-enabled/gitea
        state: link
      when: inventory_hostname in ['gitea']

    - name: Restart nginx...
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: restarted
      when: inventory_hostname in ['gitea']
