---
- name: Deploy syslog configuration
  hosts: all
  user: ansible
  become: true

  tasks:
    - name: Copy config file - client
      ansible.builtin.copy:
        src: ./templates/rsyslog.client.conf
        dest: /etc/rsyslog.conf
        mode: '0644'
      when: "'syslogsrv' not in inventory_hostname"

    - name: Copy config file - server
      ansible.builtin.copy:
        src: ./templates/rsyslog.server.conf
        dest: /etc/rsyslog.conf
        mode: '0644'
      when: "'syslogsrv' in inventory_hostname"

    - name: Reloads systemd daemon configuration
      ansible.builtin.shell: systemctl daemon-reload

    - name: Restart service
      ansible.builtin.systemd:
        name: rsyslog
        enabled: yes
        state: restarted
