---
- name: Deploy matrix configuration
  hosts: matrix
  user: ansible
  become: true

  tasks:
    - name: Copy config file
      ansible.builtin.copy:
        src: ./templates/conduit.toml
        dest: /etc/conduit/conduit.toml
        mode: '0644'

    - name: Copy service file
      ansible.builtin.copy:
        src: ./templates/conduit.service
        dest: /etc/systemd/system/conduit.service
        mode: '0644'

    - name: Reloads systemd daemon configuration
      ansible.builtin.shell: systemctl daemon-reload

    - name: Stopping service
      ansible.builtin.systemd:
        name: conduit
        enabled: yes
        state: stopped

    - name: Pausing to ensure orderly restart...
      ansible.builtin.pause:
        seconds: 5

    - name: Starting service
      ansible.builtin.systemd:
        name: conduit
        enabled: yes
        state: started
